name: Main Workflow
# this is main workflow that will run on push and pr's to main branch

on:
  push:
    branches:
      - main

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout code
        uses: actions/checkout@v3

        # set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      # Set new version of app
      - name: Set new version of app
        env:
          CURRENT_VERSION: ${{ secrets.APP_VERSION }}
        run: |
          CURRENT_VERSION=$((CURRENT_VERSION + 1))
          CODE_VERSION=$((CURRENT_VERSION + 1))
          sed -i "/version:/c version: 1.0.$CURRENT_VERSION+$CODE_VERSION" pubspec.yaml
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      # create .env file with Firebase secrets
      - name: Create .env file
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" > .env
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }}" >> .env

        # install dependencies
      - name: Install dependencies
        run: flutter pub get

        # lint with dart analyzer
      - name: Analyze code
        run: flutter analyze

        # runs tests
      - name: Run tests
        run: flutter test

        # build release apk
      - name: Build APK
        run: flutter build apk --release

        # upload to firebase app distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
          groups: "testers"
          file: build/app/outputs/flutter-apk/app-release.apk

      # Update GitHub repo secret for future app builds
      - name: Update GitHub repo secret for future app builds
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'APP_VERSION'
          value: ${{ env.CURRENT_VERSION }}
          repository: AkmenZ/crewlink_project2025
          token: ${{ secrets.GH_PAT }}
